# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/jan/Documents/Research/Projects/EMILY Tracker/Code/EMILYTracker2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/jan/Documents/Research/Projects/EMILY Tracker/Code/EMILYTracker2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jan/Documents/Research/Projects/EMILY Tracker/Code/EMILYTracker2/CMakeFiles" "/Users/jan/Documents/Research/Projects/EMILY Tracker/Code/EMILYTracker2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jan/Documents/Research/Projects/EMILY Tracker/Code/EMILYTracker2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EMILYTracker

# Build rule for target.
EMILYTracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EMILYTracker
.PHONY : EMILYTracker

# fast build rule for target.
EMILYTracker/fast:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/build
.PHONY : EMILYTracker/fast

Command.o: Command.cpp.o

.PHONY : Command.o

# target to build an object file
Command.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Command.cpp.o
.PHONY : Command.cpp.o

Command.i: Command.cpp.i

.PHONY : Command.i

# target to preprocess a source file
Command.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Command.cpp.i
.PHONY : Command.cpp.i

Command.s: Command.cpp.s

.PHONY : Command.s

# target to generate assembly for a file
Command.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Command.cpp.s
.PHONY : Command.cpp.s

Communication.o: Communication.cpp.o

.PHONY : Communication.o

# target to build an object file
Communication.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Communication.cpp.o
.PHONY : Communication.cpp.o

Communication.i: Communication.cpp.i

.PHONY : Communication.i

# target to preprocess a source file
Communication.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Communication.cpp.i
.PHONY : Communication.cpp.i

Communication.s: Communication.cpp.s

.PHONY : Communication.s

# target to generate assembly for a file
Communication.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Communication.cpp.s
.PHONY : Communication.cpp.s

Control.o: Control.cpp.o

.PHONY : Control.o

# target to build an object file
Control.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Control.cpp.o
.PHONY : Control.cpp.o

Control.i: Control.cpp.i

.PHONY : Control.i

# target to preprocess a source file
Control.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Control.cpp.i
.PHONY : Control.cpp.i

Control.s: Control.cpp.s

.PHONY : Control.s

# target to generate assembly for a file
Control.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Control.cpp.s
.PHONY : Control.cpp.s

Logger.o: Logger.cpp.o

.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

OutputVideo.o: OutputVideo.cpp.o

.PHONY : OutputVideo.o

# target to build an object file
OutputVideo.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/OutputVideo.cpp.o
.PHONY : OutputVideo.cpp.o

OutputVideo.i: OutputVideo.cpp.i

.PHONY : OutputVideo.i

# target to preprocess a source file
OutputVideo.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/OutputVideo.cpp.i
.PHONY : OutputVideo.cpp.i

OutputVideo.s: OutputVideo.cpp.s

.PHONY : OutputVideo.s

# target to generate assembly for a file
OutputVideo.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/OutputVideo.cpp.s
.PHONY : OutputVideo.cpp.s

Settings.o: Settings.cpp.o

.PHONY : Settings.o

# target to build an object file
Settings.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Settings.cpp.o
.PHONY : Settings.cpp.o

Settings.i: Settings.cpp.i

.PHONY : Settings.i

# target to preprocess a source file
Settings.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Settings.cpp.i
.PHONY : Settings.cpp.i

Settings.s: Settings.cpp.s

.PHONY : Settings.s

# target to generate assembly for a file
Settings.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Settings.cpp.s
.PHONY : Settings.cpp.s

Undistort.o: Undistort.cpp.o

.PHONY : Undistort.o

# target to build an object file
Undistort.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Undistort.cpp.o
.PHONY : Undistort.cpp.o

Undistort.i: Undistort.cpp.i

.PHONY : Undistort.i

# target to preprocess a source file
Undistort.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Undistort.cpp.i
.PHONY : Undistort.cpp.i

Undistort.s: Undistort.cpp.s

.PHONY : Undistort.s

# target to generate assembly for a file
Undistort.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/Undistort.cpp.s
.PHONY : Undistort.cpp.s

UserInterface.o: UserInterface.cpp.o

.PHONY : UserInterface.o

# target to build an object file
UserInterface.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/UserInterface.cpp.o
.PHONY : UserInterface.cpp.o

UserInterface.i: UserInterface.cpp.i

.PHONY : UserInterface.i

# target to preprocess a source file
UserInterface.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/UserInterface.cpp.i
.PHONY : UserInterface.cpp.i

UserInterface.s: UserInterface.cpp.s

.PHONY : UserInterface.s

# target to generate assembly for a file
UserInterface.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/UserInterface.cpp.s
.PHONY : UserInterface.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/EMILYTracker.dir/build.make CMakeFiles/EMILYTracker.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... EMILYTracker"
	@echo "... Command.o"
	@echo "... Command.i"
	@echo "... Command.s"
	@echo "... Communication.o"
	@echo "... Communication.i"
	@echo "... Communication.s"
	@echo "... Control.o"
	@echo "... Control.i"
	@echo "... Control.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... OutputVideo.o"
	@echo "... OutputVideo.i"
	@echo "... OutputVideo.s"
	@echo "... Settings.o"
	@echo "... Settings.i"
	@echo "... Settings.s"
	@echo "... Undistort.o"
	@echo "... Undistort.i"
	@echo "... Undistort.s"
	@echo "... UserInterface.o"
	@echo "... UserInterface.i"
	@echo "... UserInterface.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

